vich_uploader:
    db_driver: orm

    mappings:
        pin_image:
            uri_prefix: /images1/loan
            upload_destination: '%kernel.project_dir%/public/images1/loan'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


