version: '3'

services:
  nginx:
    container_name: app-loan-nginx
    build: docker/nginx
    working_dir: /var/www/app
    ports:
      - '9889:80'
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default-compose.conf:/etc/nginx/conf.d/default-compose.conf
    networks:
      - app-loan-network

  php:
    container_name: app-loan-fpm
    build: docker/php
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - app-loan-network

  mysql:
    container_name: app-loan-mysql
    build: docker/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-loan-network

  phpmyadmin:
    container_name: app-loan-phpmyadmin
    build: docker/phpmyadmin
    restart: on-failure
    ports:
      - 7778:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini
    networks:
      - app-loan-network

  maildev:
    image: maildev/maildev
    container_name: app-loan-maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 9959:80
    restart: on-failure
    networks:
      - app-loan-network

  blackfire:
    image: blackfire/blackfire
    container_name: blackfire_symfony
    ports: ["8707"]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
    networks:
      - app-loan-network

networks:
  app-loan-network: